<?php

/**
 * AdminUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdminUsersTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object AdminUsersTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('AdminUsers');
    }

    public static function loginData($username, $password) {
        $q = Doctrine_Query::create()
                ->select('au.*')
                ->from('AdminUsers au')
                ->where('au.username=?', trim($username))
                ->andWhere('au.password=?', md5($password))
                ->setHydrationMode(Doctrine::HYDRATE_SCALAR)
                ->fetchOne();

        if (count($q) > 0)
            return $q;
        return false;
    }

}
