<?php

/**
 * LookupIndustriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LookupIndustriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LookupIndustriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LookupIndustries');
    }
    
    public static function getAllIndustries() {
        return Doctrine_Query::create()
                ->select('i.*')
                ->from('LookupIndustries i')
                ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->execute();
    }
}