<?php

/**
 * LookupJobRolesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LookupJobRolesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LookupJobRolesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LookupJobRoles');
    }
    
    public static function getAllJobRoles() {
        return Doctrine_Query::create()
                ->select('jr.*')
                ->from('LookupJobRoles jr')
                ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->execute();
    }
}