<?php

/**
 * LookupCountriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LookupCountriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LookupCountriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LookupCountries');
    }
}