<?php

/**
 * LookupCareersLevelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LookupCareersLevelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LookupCareersLevelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LookupCareersLevel');
    }
}