<?php

/**
 * NewsletterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsletterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsletterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Newsletter');
    }
    
    public static function getObject($table, $field_name, $id) {
        return Doctrine_Query::create()
                ->select("o.{$field_name}")
                ->from("{$table} o")
                ->where('o.id =?', $id)
                ->setHydrationMode(Doctrine::HYDRATE_SCALAR)
                ->fetchOne();
    }
}