<?php

/**
 * OpportunitesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpportunitesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OpportunitesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Opportunites');
    }
}