<?php

/**
 * ProductsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Products');
    }
    
    public static function getOne($id) {
        return Doctrine_Query::create()
                ->select('p.*, pc.name, pc.banner_file')
                ->from('Products p, p.ProductCategories pc')
                ->where('p.id =?', $id)
                ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->fetchOne();
    }

    public static function getAllCategoryProducts($cat_id, $active = FALSE) {
        $q = Doctrine_Query::create()
                ->select('p.*, pc.id')
                ->from('Products p, p.ProductCategories pc')
                ->where('pc.id =?', $cat_id)
                ->andWhere('p.deleted=0');
        if ($active) {
            $q = $q->andWhere('p.is_active=?', TRUE);
        }
        $q = $q->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->execute();
        
        return $q;
    }
}