<?php

/**
 * ProductCategoriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductCategoriesTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ProductCategoriesTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ProductCategories');
    }
    
    public static function getOne($id) {
        return Doctrine_Query::create()
                ->select('pc.*')
                ->from('ProductCategories pc')
                ->where('pc.id =?', $id)
                ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->fetchOne();
    }

    public static function getAllCategories($active = FALSE, $lang_id = 1) {
        $q = Doctrine_Query::create()
                ->select('pc.*')
                ->from('ProductCategories pc')
                ->where('pc.lang_id =?', $lang_id)
                ->andwhere('pc.deleted =0');
        if ($active) {
            $q = $q->andWhere('pc.is_active=?', TRUE);
        }
        $q = $q->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->execute();
        
        return $q;
    }

}
