<?php

/**
 * Profiles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Profiles extends BaseProfiles
{
    public function addApplication(array $data) {
        $a = new Profiles();
        $a->name = $data['name'];
        $a->position = $data['position'];
        $a->email = $data['email'];
        $a->country_id = $data['country_id'];
        $a->city = $data['city'];
        $a->mobile = $data['mobile'];
        $a->cv_file = $data['cv_file'];
        $a->created_at = date('ymdHis');
        $a->save();
        
        return $a->id;
    }
}