<?php

/**
 * StaticPagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StaticPagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StaticPagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StaticPages');
    }
    
    public static function getOne($page_id, $lang_id = 1) {
        return Doctrine_Query::create()
                ->select('p.*')
                ->from('StaticPages p')
                ->where('p.page_id =?', $page_id)
                ->andWhere('p.lang_id =?', $lang_id)
                ->setHydrationMode(Doctrine::HYDRATE_ARRAY)
                ->fetchOne();
    }
}