<?php

/**
 * UsersOpportunitiesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsersOpportunitiesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsersOpportunitiesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsersOpportunities');
    }
}