<?php

/**
 * UsersOpportunities
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UsersOpportunities extends BaseUsersOpportunities
{
    public function addApplication($profile_id, $opportunity_id) {
        $uo = new UsersOpportunities();
        $uo->profile_id = $profile_id;
        $uo->opportunity_id = $opportunity_id;
        $uo->save();
    }
}