<?php

/**
 * WebsiteLanguagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebsiteLanguagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebsiteLanguagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebsiteLanguages');
    }
}